export const SHEET_ID_QUIZ = "PASTE_QUIZ_GOOGLE_SHEET_ID_HERE";
export const SHEET_ID_FEEDBACK = "PASTE_FEEDBACK_GOOGLE_SHEET_ID_HERE";
export const DONATION_URL = "PASTE_LIVE_DONATION_LINK_HERE";
export const TALLY_FORM_ID_QUIZ = "3qlZQ9";
export const TALLY_FORM_ID_FEEDBACK = "nGPKDo";
