export const env = {
  API_BASE: process.env.API_BASE,
  WORKER_KEY: process.env.WORKER_KEY,
  MAGS_KEY: process.env.MAGS_KEY,
  CRON_SECRET: process.env.CRON_SECRET,
  NOTION_TOKEN: process.env.NOTION_TOKEN,
  NOTION_DATABASE_ID: process.env.NOTION_DATABASE_ID,
  NOTION_INBOX_PAGE_ID: process.env.NOTION_INBOX_PAGE_ID,
  NOTION_HQ_PAGE_ID: process.env.NOTION_HQ_PAGE_ID,
  BROWSERLESS_API_KEY: process.env.BROWSERLESS_API_KEY,
  BROWSERLESS_TOKEN: process.env.BROWSERLESS_TOKEN || process.env.BROWSERLESS_API_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  NOTION_STRIPE_DB_ID: process.env.NOTION_STRIPE_DB_ID,
  NOTION_DB_RUNS_ID: process.env.NOTION_DB_RUNS_ID,
  NOTION_QUEUE_DB_ID: process.env.NOTION_QUEUE_DB_ID,
  NOTION_QUEUE_DB: process.env.NOTION_QUEUE_DB,
  NOTION_SOCIAL_DB: process.env.NOTION_SOCIAL_DB,
  DRIVE_PRODUCT_IMAGES_ROOT_ID: process.env.DRIVE_PRODUCT_IMAGES_ROOT_ID,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_FROM: process.env.RESEND_FROM,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
  TELEGRAM_CALLBACK_SECRET: process.env.TELEGRAM_CALLBACK_SECRET,
  TALLY_API_KEY: process.env.TALLY_API_KEY,
  TALLY_WEBHOOK_SECRET: process.env.TALLY_WEBHOOK_SECRET,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  MASTER_MEMORY_SHEET_ID: process.env.MASTER_MEMORY_SHEET_ID,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  MM_DRIVE_ROOT_ID: process.env.MM_DRIVE_ROOT_ID,
  CHAN_DRIVE_ROOT_ID: process.env.CHAN_DRIVE_ROOT_ID,
  MM_DRIVE_INBOX_ID: process.env.MM_DRIVE_INBOX_ID,
  MM_DRIVE_REVIEW_ID: process.env.MM_DRIVE_REVIEW_ID,
  MM_DRIVE_READY_ID: process.env.MM_DRIVE_READY_ID,
  MM_DRIVE_ARCHIVE_ID: process.env.MM_DRIVE_ARCHIVE_ID,
  MM_DRIVE_FAILED_ID: process.env.MM_DRIVE_FAILED_ID,
  MM_DRIVE_CHANCUB_PARENT_ID: process.env.MM_DRIVE_CHANCUB_PARENT_ID,
  MM_DRIVE_MM_PARENT_ID: process.env.MM_DRIVE_MM_PARENT_ID,
  SALES_TAX_STATE: process.env.SALES_TAX_STATE,
  SALES_TAX_ZIP: process.env.SALES_TAX_ZIP,
  DALL_E_STYLE_PROMPT: process.env.DALL_E_STYLE_PROMPT,
  DRY_RUN: process.env.DRY_RUN === '1' || process.env.DRY_RUN === 'true',
  ALLOWED_DOMAINS: (process.env.ALLOWED_DOMAINS || '')
    .split(',')
    .map((d) => d.trim())
    .filter(Boolean),
  EXECUTION_PAUSED: process.env.EXECUTION_PAUSED === '1' || process.env.EXECUTION_PAUSED === 'true',
};

export function requireEnv(name) {
  const v = env[name];
  if (!v) throw new Error(`Missing env: ${name}`);
  return v;
}
