name: context-sync

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: Build context
        id: build
        run: node --experimental-strip-types ops/context/build_context.ts
      - name: Detect changes
        id: diff
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git status --short docs public/context.html > changes.txt
          if [ -s changes.txt ]; then
            git add docs public/context.html
            git commit -m "chore: update context docs"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Push changes
        if: steps.diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.diff.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const files = fs.readFileSync('changes.txt', 'utf8').trim().split('\n').map(l => l.split(' ').pop()).join(', ');
            const body = `Context updated: ${files}`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
