name: context-sync

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Enable corepack (future-proof)
        run: corepack enable || true

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Lint (optional)
        run: npm run lint --if-present
