name: mags-cron
on:
  schedule: [{ cron: "*/10 * * * *" }]
  workflow_dispatch: {}
  repository_dispatch:
    types: [mags-run-queue]

jobs:
  run-queue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Claim next job
        id: claim
        env:
          API_BASE: https://mags-assistant.vercel.app
          WORKER_KEY: ${{ secrets.WORKER_KEY }}
        run: |
          set -e
          curl -fsS -X POST "$API_BASE/api/queue/next" \
            -H "X-Worker-Key: $WORKER_KEY" \
            -H "content-type: application/json" \
            -o job.json
          cat job.json

      - name: Process job
        if: ${{ hashFiles('job.json') != '' }}
        env:
          API_BASE: https://mags-assistant.vercel.app
          WORKER_KEY: ${{ secrets.WORKER_KEY }}
        run: |
          set -e
          curl -fsS -X POST "$API_BASE/api/queue/run" \
            -H "X-Worker-Key: $WORKER_KEY" \
            -H "content-type: application/json" \
            --data-binary @job.json

      - name: Log success
        if: ${{ success() }}
        run: echo "Mags queue run OK at $(date -u)"

      - name: On failure notify
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.ALERT_EMAIL_USER }}
          password: ${{ secrets.ALERT_EMAIL_PASS }}
          subject: "Mags queue failure"
          to: ${{ secrets.ALERT_TO }}
          from: "mags@messyandmagnetic.com"
          body: "Check GitHub Actions logs."
