name: mags-cron

on:
  schedule:
    - cron: "*/10 * * * *"   # run every 10 minutes
  workflow_dispatch: {}
  repository_dispatch:
    types: [mags-run-queue]

permissions:
  contents: read

jobs:
  run-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Claim next job
        env:
          API_BASE: ${{ secrets.API_BASE }}           # e.g. https://mags-assistant.vercel.app
          WORKER_KEY: ${{ secrets.WORKER_KEY }}       # same shared key your API expects in X-Worker-Key
        run: |
          set -euo pipefail
          curl -fsS -X POST "$API_BASE/api/queue/claim" \
            -H "X-Worker-Key: $WORKER_KEY" \
            -H "content-type: application/json" \
            -o job.json || echo '{}' > job.json
          cat job.json

      - name: Exit if no job
        run: |
          jq -e '.jobId' job.json >/dev/null || { echo "No job available"; exit 0; }

      - name: Run job
        env:
          API_BASE: ${{ secrets.API_BASE }}
        run: |
          curl -fsS -X POST "$API_BASE/api/queue/run" \
            -H "content-type: application/json" \
            --data-binary @job.json

      - name: Complete job
        if: always()
        env:
          API_BASE: ${{ secrets.API_BASE }}
          WORKER_KEY: ${{ secrets.WORKER_KEY }}
        run: |
          JOB_ID=$(jq -r '.jobId // empty' job.json)
          if [ -n "$JOB_ID" ]; then
            curl -fsS -X POST "$API_BASE/api/queue/complete" \
              -H "X-Worker-Key: $WORKER_KEY" \
              -H "content-type: application/json" \
              --data-binary @job.json || true
          fi
