name: mags-cron

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      API_BASE: ${{ secrets.API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Trigger scan
        shell: bash
        run: |
          set -euo pipefail
          curl -sS -X POST "$API_BASE/api/commands/scan" \
            -H "x-mags-key: $CRON_SECRET" \
            -H "content-type: application/json" \
            -d '{}' \
            | tee scan.json
      - name: Run due social posts
        if: env.API_BASE == 'https://mags-assistant.vercel.app'
        shell: bash
        run: |
          set -euo pipefail
          curl -sS -X POST "$API_BASE/api/social/run-due" \
            -H "x-mags-key: $CRON_SECRET" \
            -H "content-type: application/json" \
            -d '{}' \
            | tee social.json
