name: mags-cron

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      USE_GH_CRON: ${{ secrets.USE_GH_CRON }}
      API_BASE: ${{ secrets.API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Check cron flag
        run: |
          if [ "$USE_GH_CRON" != "true" ]; then
            echo "skipped by USE_GH_CRON"
            exit 0
          fi
      - name: Check API base
        run: |
          if [ -z "$API_BASE" ]; then
            echo "API_BASE empty; skipping API calls"
            exit 0
          fi
      - name: Trigger scan
        run: |
          set -euo pipefail
          curl -sS -X POST "$API_BASE/api/commands/scan" \
            -H "x-mags-key: $CRON_SECRET" \
            -H "content-type: application/json" \
            -d '{}' \
            | tee scan.json
      - name: Run due social posts
        if: env.API_BASE == 'https://mags-assistant.vercel.app'
        run: |
          set -euo pipefail
          curl -sS -X POST "$API_BASE/api/social/run-due" \
            -H "x-mags-key: $CRON_SECRET" \
            -H "content-type: application/json" \
            -d '{}' \
            | tee social.json
      - name: Send run log to Telegram
        if: env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != ''
        run: |
          curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="cron-runner workflow run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
