name: Drive Review Ping
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      PROD_URL: ${{ secrets.PROD_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Check PROD_URL
        id: check
        run: |
          if [ -n "$PROD_URL" ] && curl -I -sS "$PROD_URL" | head -n 1 | grep -q "200"; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "Prod URL missing or unreachable; skipping ping."
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Call Vercel endpoint
        if: steps.check.outputs.ok == 'true'
        run: |
          curl -fsS "$PROD_URL/api/drive/review?token=$CRON_SECRET"
