name: gmail_sync

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Gmail land sync
        env:
          GMAIL_ACCESS_TOKEN: ${{ secrets.GMAIL_ACCESS_TOKEN }}
          GMAIL_APPS_SCRIPT_URL: ${{ secrets.GMAIL_APPS_SCRIPT_URL }}
          CF_WORKER_NAME: ${{ secrets.CF_WORKER_NAME }}
        run: node scripts/gmail-land-sync.mjs
      - name: Commit inbox snapshot
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/.inbox-land.json
          git commit -m "chore: update inbox" || echo "no changes"
          git push
      - name: Send run log to Telegram
        if: secrets.TELEGRAM_BOT_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != ''
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="gmail_sync run: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
