name: grants-scout
on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  scout:
    runs-on: ubuntu-latest
    env:
      API_BASE: ${{ secrets.WORKER_URL }}
      FETCH_PASS: ${{ secrets.WORKER_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Search NM grants
        run: |
          if [ -z "$API_BASE" ]; then echo "missing API_BASE, skipping"; exit 0; fi
          curl -sS -X POST "$API_BASE/grants/scout?state=NM" -H "X-Fetch-Pass: $FETCH_PASS" || true
      - name: Send run log to Telegram
        if: env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != ''
        run: |
          curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="grants-scout workflow run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
