name: Smoke Health Check

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Ping production healthz
        run: |
          set -e
          curl -fsSL https://mags-assistant.vercel.app/healthz.txt | grep -qi "^ok$"
