name: Smoke Health Check
on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Check production /api/ping
        run: |
          set -euxo pipefail
          curl -fsS --max-time 15 https://mags-assistant.vercel.app/api/ping
