name: Smoke Health Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Check /api/health
        run: curl -fsS https://assistant.messyandmagnetic.com/api/health
