name: memory-clean

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DB_MEMORY: ${{ secrets.NOTION_DB_MEMORY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Compact memory DB
        run: npx tsx scripts/memory/compact.ts
