name: Nightly analytics
on:
  schedule: [{ cron: "15 7 * * *" }]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      API_BASE: ${{ secrets.API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Compute API availability
        run: |
          if [ -n "$API_BASE" ]; then
            echo "HAS_API=true" >> "$GITHUB_ENV"
          else
            echo "HAS_API=false" >> "$GITHUB_ENV"
          fi
      - name: Hit analyze endpoint
        if: env.HAS_API == 'true'
        run: curl -fsS "$API_BASE/api/social/analyze?token=$CRON_SECRET"
      - name: No API base
        if: env.HAS_API != 'true'
        run: echo "No API_BASE; skipping analytics"
      - name: Telegram ping
        if: env.HAS_API != 'true' && env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != ''
        run: |
          curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="nightly analytics skipped"
