name: Post Scheduler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Schedule clips
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - <<'PY'
import json, os, pathlib, datetime, requests
log_path = pathlib.Path('public/mags-log.json')
log = json.load(log_path.open()) if log_path.exists() else {"clips": []}
count = 0
token = os.environ.get('TELEGRAM_BOT_TOKEN')
chat = os.environ.get('TELEGRAM_CHAT_ID')
for clip in log.get('clips', []):
    ts = clip.setdefault('timestamps', {})
    if clip.get('status') == 'matched' and not ts.get('scheduled'):
        ts['scheduled'] = datetime.datetime.utcnow().isoformat() + 'Z'
        clip['status'] = 'scheduled'
        count += 1
        if token and chat:
            text = f"Scheduled {clip.get('path','')}"
            requests.post(f'https://api.telegram.org/bot{token}/sendMessage', json={'chat_id': chat, 'text': text})
        if count >= 12:
            break
json.dump(log, log_path.open('w'), indent=2)
PY
