name: site

on:
  push:
    paths:
      - 'site/**'
      - '.github/workflows/site.yml'
  pull_request:
    paths:
      - 'site/**'
      - '.github/workflows/site.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm --filter site build
      - run: pnpm --filter site test
