name: smoke

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read
  pull-requests: write  # lets the job comment when allowed

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Get preview URL from Vercel
        id: vercel
        run: |
          node scripts/get-vercel-preview.js > preview.txt || true
          URL=$(cat preview.txt 2>/dev/null || echo "")
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Smoke test /api/ping
        if: ${{ steps.vercel.outputs.url != '' }}
        run: |
          curl -fsSL "${{ steps.vercel.outputs.url }}/api/ping"

      - name: Preview unavailable (informative)
        if: ${{ steps.vercel.outputs.url == '' }}
        run: echo "No READY preview deployment found yet."

      # Only try to comment if token has permission and we have a PR context
      - name: Comment preview URL
        if: >
          github.event_name == 'pull_request' &&
          steps.vercel.outputs.url != '' &&
          env.CAN_COMMENT == 'true'
        env:
          CAN_COMMENT: ${{ github.token != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const body = `Preview: ${process.env.URL}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          URL: ${{ steps.vercel.outputs.url }}