name: smoke-intake
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GAS_INTAKE_URL: ${{ secrets.GAS_INTAKE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: node scripts/smoke-intake.mjs
