name: smoke

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      API_BASE: ${{ secrets.API_BASE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Compute API availability
        run: |
          if [ -n "$API_BASE" ]; then
            echo "HAS_API=true" >> "$GITHUB_ENV"
          else
            echo "HAS_API=false" >> "$GITHUB_ENV"
          fi

      - name: Check static health
        run: |
          set -euo pipefail
          curl -fsS https://mags-assistant.vercel.app/health.json -o /tmp/health.json --max-time 8
          node -e "const j=require('fs').readFileSync('/tmp/health.json','utf8'); const o=JSON.parse(j); if(!o.ok) { console.error('health.ok != true'); process.exit(1) }"

      - name: Check Worker (non-blocking)
        run: |
          set -euo pipefail
          url="https://tight-snow-2840.messyandmagnetic.workers.dev"
          code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 6 "$url" || true)
          echo "Worker HTTP $code"

      - name: Smoke test API ping
        if: env.HAS_API == 'true'
        run: |
          curl -sSf "$API_BASE/api/ping" | tee /dev/stdout

      - name: Notify failure
        if: failure() && env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != ''
        run: node scripts/notify.ts "❌ smoke failed: $GITHUB_RUN_ID"

      - name: Telegram success
        if: success() && env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != ''
        run: |
          curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ Smoke passed at $(date --iso-8601=seconds)"
