name: stripe-sync

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Run Stripe ↔ Notion audit
        id: audit
        run: |
          OUT=$(curl -sS "$API_BASE/api/stripe/sync?mode=audit&dry=1" -H "Cookie: mags-chat=$CHAT_PASSWORD")
          echo "$OUT"
          echo "$OUT" > out.json
          node -e "const o=require('./out.json');const bad=o.report && (o.report.missingInStripe.length||o.report.missingInNotion.length||o.report.mismatches.length||o.report.duplicates.length);if(bad)process.exit(1)"
        env:
          API_BASE: ${{ secrets.API_BASE }}
          CHAT_PASSWORD: ${{ secrets.CHAT_PASSWORD }}
      - name: Notify on issues
        if: failure()
        run: npx tsx scripts/announce.ts "Stripe sync needs attention"
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
